### ISSUE TITLE
Could it be that the reporter itself is crashing?

### ISSUE THREAD

**Issue by rugk** [choller/firefox-asan-reporter#2]
When Firefox crashes, should not I get this usual crash reporter as in the stable versions? Or does it this reporter handle it automatically/on the fly/in the background?

When I get this message in the console:
```
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=479.918) %                                                                  Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=457.606) AddressSanitizer:DEADLYSIGNAL
```

Does that mean ASan itself crashed?

(asking because of such stuff in https://bugzilla.mozilla.org/show_bug.cgi?id=1479319)

**Comment by choller** [comment]
The ASan Nightly builds do not use the regular crash reporter, it is disabled.

Instead, they use an addon that both scans for crashes at startup to submit, but also is notified if a content process crashes, so the crash can be submitted in the background without restarting the browser.

What you pasted here indicates that a Firefox process (maybe the GFX process?) crashed. The second DEADLYSIGNAL can be from the parent, as in some cases, we do not recover from IPC failures and force a crash in the parent as well. All of this looks normal though, one crash can lead to multiple crash reports. If the parent dies, crashes will be submitted on startup.

**Comment by rugk** [comment]
Okay, good. Thanks for the fast information. :smile: 

But if you are already here? `about:crashes` in Firefox ASan does not exist. Is there any way to get crash report IDs? Or something like this?

**Comment by choller** [comment]
There is no such thing as a crash report ID right now. The submitted reports are stored in the profile directory though, in a sub directory called "asan". I'm planning to add about:crashes as a simple directory listing of that directory later maybe (there is a bug on file for this).

**Comment by rugk** [comment]
Okay, thanks.
